# Generated by Django 4.0.3 on 2023-12-21 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='customer',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='appointment',
            unique_together={('customer', 'date_time')},
        ),
    ]
